Olha_US_1
mregall/Group29_NextBaseCRM pull request #2
Opened 2022-06-21 19:26 UTC by olha1039

2022-06-21 19:27 UTC, mregall requested changes
CRMLoginUtil not working.

2022-06-21 19:28 UTC, olha1039 commented
working on it

2022-06-22 02:09 UTC, olha1039 commented
ConfigurationReader was added to all test cases

2022-06-27 16:43 UTC, mregall approved these changes

2022-06-27 16:44 UTC, merged